### ISSUE TITLE
`open-input-file: cannot open module file` When trying to run file in terminal on Windows

### ISSUE THREAD

**Issue by shengjiex98** [Eugleo/magic-racket#67]
## Environment
- OS: [Windows 11]
- OS Version [ 21H2, build 22000.434 ]
- VS Code Version [1.63.2]
- Racket version [8.3]
- Racket Langserver checksum [a1141f0871a55c036949d0bb0179fddbf86a97cd]
- Magic Racket version [0.6.2] 

## Error message
```
PS C:\Users\Shengjie\Desktop> racket c\:/Users/Shengjie/Desktop/test.rkt
open-input-file: cannot open module file
  module path: C:\Users\Shengjie\Desktop\c\:\Users\Shengjie\Desktop\test.rkt
  path: C:\Users\Shengjie\Desktop\c\:\Users\Shengjie\Desktop\test.rkt
  system error: The filename, directory name, or volume label syntax is incorrect.; win_err=123
```

## Additional context
This occurs when trying to click the green arrow `Racket: run file in terminal`. Running the command mannual without the `\` inserted in the path (i.e. running `racket c\:/Users/Shengjie/Desktop/test.rkt` manually can run the file just fine.

---

_If relevant, please enclose a minimal example file which triggers the errors. If you're unable to enclose the file, please do the following instead:_

No log is generated. Here's the test file:
```
#lang racket

(+ 1 2)
```

**Comment by CatEricka** [comment]
Duplicate of #63

**Comment by shengjiex98** [comment]
> Duplicate of #63

Thanks for pointing it out. As I understand it the marketplace version is not fixed yet, correct?

**Comment by CatEricka** [comment]
> Thanks for pointing it out. As I understand it the marketplace version is not fixed yet, correct?

https://marketplace.visualstudio.com/items/evzen-wybitul.magic-racket/changelog

Version 0.6.2 fixes this, try updating to the latest version or reinstalling the extension.

**Comment by CatEricka** [comment]
> Version 0.6.2 fixes this

...I don't understand, the bug still exists in 0.6.2

**Comment by CatEricka** [comment]
I checked the code of version 0.6.2 which download by:

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/evzen-wybitul/vsextensions/magic-racket/0.6.2/vspackage

marketplace version repl.js:

```javascript
exports.executeSelectionInRepl = executeSelectionInRepl;
function runFileInTerminal(command, filePath, terminal) {
    terminal.show();
    terminal.sendText(`clear`);
    terminal.sendText((0, shell_quote_1.quote)([...command, filePath]));
    // Leaving this here if we ever need to fix cmd.exe again
    // const shell: string | undefined = vscode.workspace
    //   .getConfiguration("terminal.integrated.shell")
    //   .get("windows");
    // if (process.platform === "win32" && shell && /cmd\.exe$/.test(shell)) {
    //   // cmd.exe doesn't recognize single quotes
    //   terminal.sendText(`${racket} "${filePath}"`);
    // } else {
    //   terminal.sendText(`${racket} '${filePath}'`);
    // }
}
```

fixed version repl.ts:

```typescript
export function runFileInTerminal(
  command: string[],
  filePath: string,
  terminal: vscode.Terminal,
): void {
  terminal.show();
 
  if (isWindowsOS()) {
    terminal.sendText(isPowershellShell() || isCmdExeShell() ? `cls` : `clear`);
    const racketExePath = quoteWindowsPath(command[0], true);
    filePath = quoteWindowsPath(filePath, false);
    terminal.sendText(`${racketExePath} ${command.slice(1).join(' ')} ${filePath}`);
  } else {
    terminal.sendText(`clear`);
    terminal.sendText(quote([...command, filePath]));
  }
}
```

Looks like the wrong file was packaged and published.

**Comment by shengjiex98** [comment]
That makes sense. Should I close the issue, or keep it open until it is fixed in the released version?

**Comment by CatEricka** [comment]
Maybe should keep it open and wait for the author to merge pr (#68) to release a new version ?

**Comment by Eugleo** [comment]
Should be fixed in 0.6.3. Made sure to package the correct code this time.

**Comment by Maxwise** [comment]
v 0.6.3 still not work under Windows
![image](https://user-images.githubusercontent.com/5328369/155394048-33ff52a4-018e-40ee-8838-0e0b3b1ff35b.png)

**Comment by hamidb80** [comment]
**this is wrong path:**
```
c:/Users/play.rkt
```

the correct path is:
```
C://Users/play.rkt
```

**Comment by hamidb80** [comment]
I'm sorry that I was wrong in the last comment. I new to Racket. the problem is not from generated path.

It's so strange that `Racket: Load file in REPL` button doesn't work for the first time, but it works after that.
see what I mean:

![image](https://user-images.githubusercontent.com/33871336/156242581-364a86c0-2e1c-42e9-8973-1dfcf0d7b3a3.png)

as you can see, the first time that the extension passed the code with `--eval` flag, it raises an error, but the second time that I clicked on that button, it works fine.

**Comment by CatEricka** [comment]
@hamidb80 It's magic-racket's issue (#66) which has been fixed but not published properly: https://github.com/Eugleo/magic-racket/issues/66#issuecomment-1022130597

**Comment by Eugleo** [comment]
Should be fixed. I manually downloaded the 0.6.4 from the marketplace and checked that the `repl.js` file is the correct one. Sorry everyone for the mishaps!
